"""
Constants File
"""

AUDIO_PHRASE_TIME_LIMIT = 5
MAX_VOLUME_THRESHOLD = 10
GPT_4 = 'gpt-4'
GPT_4_MODEL = "gpt-4o-mini"
GPT_35_MODEL = "gpt-3.5-turbo"
MAX_LOOP = 3
ELLIPSIS = "..."
CONTINUATION_PROMPT = '... '
PYTHON_PROMPT = '>>> '
PYTHON_SHELL = '>>>'
MAX_TOKENS = 8_000
