log_level: DEBUG
voice_control:
    use_existing_recording: False
    detect_voice: True
    send_to_llm: False
audio:
    save_recordings: True
    wake_command: "Hey Drone"
llm:
    model: gpt-4o-mini
    temperature: 0
