# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLabel
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import Qt


class MainGui(object):
    def _init_gui(self):
        self.setObjectName("MainWindow")
        self.resize(635, 523)

        # Create the background drone feed
        self.droneFeed = QtWidgets.QLabel(self)
        self.background = QPixmap("ui_starter/Aquamarine.jpg")
        self.droneFeed.setPixmap(self.background)
        self.droneFeed.setScaledContents(True)
        self.droneFeed.setGeometry(0, 0, 635, 523)
        self.droneFeed.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # Create a new central widget
        self.centralwidget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.centralwidget)

        # Create a new label for the recent command
        # Note: May also require setting a pixmap and setting the size
        self.recentCommand = QLabel("Recent command", self.centralwidget)
        self.recentCommand.setAlignment(Qt.AlignmentFlag.AlignHCenter)
        self.recentCommand.setStyleSheet("color: red; font-size: 14px;")

        # Create a new label for the recent command
        # Note: May also require setting a pixmap and setting the size
        self.videoFeed = QLabel("VideoFeed", self.centralwidget)
        self.videoFeed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.videoFeed.setStyleSheet("color: red; font-size: 14px;")

        # Add recent command and video feed labels to the central widget layout
        # Create a layout for central widget
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.layout.addWidget(self.recentCommand)
        self.layout.addWidget(self.videoFeed)
        self.centralwidget.setLayout(self.layout)
        self.centralwidget.raise_()

        # Create file menu
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.actionNew = QtGui.QAction()
        self.actionNew.setObjectName("actionNew")
        self.actionOptions = QtGui.QAction()
        self.actionOptions.setObjectName("actionOptions")
        self.actionQuit = QtGui.QAction()
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction()
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.droneFeed.setText(_translate("MainWindow", "Main drone feed"))
        self.videoFeed.setText(_translate("MainWindow", "Video feed"))
        self.recentCommand.setText(_translate("MainWindow", "Recent command"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New "))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
