drone_type: tello
mavic:
    ip: 192.168.69.244
    port: 14551
    connection_timeout: 60 # Seconds
tello:
    wifi:
        ssid: TELLO-5B59E2
        password: ""
    poll_response: false
    default_speed: 50
    video_settings_supported: false
    video_bitrate: auto
    video_resolution: 720p
    video_fps: 30
    camera_selection: forward
controller:
    connect_to_drone: true
    max_tick_rate: 30
    keyboard_bindings:
        land: l
        takeoff: 32 # Space key
        up: 16777235 # Up arrow
        down: 16777237 # Down arrow
        left: a
        right: d
        forward: w
        backward: s
        emergency: 16777223 # Delete key
        flip foward: f
        cw: e
        ccw: q
        motor on: "9"
        motor off: "0"
