drone_type: tello
gui_only: True
mavic:
    ip: 192.168.69.244
    port: 14551
    connection_timeout: 60 # Seconds
tello:
    poll_response: False
    default_speed: 50
    video_bitrate: auto
    video_resolution: 720p
    video_fps: 30
    camera_selection: forward
