# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from signals import Signals
from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel, QProgressBar, QVBoxLayout, QWidget
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel, QProgressBar, QVBoxLayout, QWidget
from PyQt6.QtGui import QPixmap
from PyQt6.QtCore import QTimer, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 523)

        self.droneFeed = QtWidgets.QLabel(self)
        self.background = QPixmap("ui_starter/Aquamarine.jpg")
        self.droneFeed.setPixmap(self.background)
        self.droneFeed.setScaledContents(True)
        self.droneFeed.setGeometry(0,0, 635, 523)
        self.droneFeed.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.centralwidget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.centralwidget)

        self.recentCommand = QLabel("Recent command", self.centralwidget)
        self.recentCommand.setAlignment(Qt.AlignmentFlag.AlignHCenter)

        self.videoFeed = QLabel("VideoFeed", self.centralwidget)
        self.videoFeed.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.layout = QtWidgets.QVBoxLayout(self.centralwidget) #Create a layout for central widget
        self.layout.addWidget(self.recentCommand)
        self.layout.addWidget(self.videoFeed)
        self.centralwidget.setLayout(self.layout)
        self.centralwidget.raise_()
        

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOptions = QtGui.QAction(parent=MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOptions)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.droneFeed.setText(_translate("MainWindow", "Main drone feed"))
        self.videoFeed.setText(_translate("MainWindow", "Video feed"))
        self.recentCommand.setText(_translate("MainWindow", "Recent command"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New "))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
    
    


    


# # Form implementation generated from reading ui file '.\ui\main.ui'
# #
# # Created by: PyQt6 UI code generator 6.7.1
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt6 import QtCore, QtGui, QtWidgets


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(626, 516)
#         self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.droneFeed = QtWidgets.QLabel(parent=self.centralwidget)
#         self.droneFeed.setGeometry(QtCore.QRect(0, 0, 621, 491))
#         self.droneFeed.setScaledContents(True)
#         self.droneFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
#         self.droneFeed.setObjectName("droneFeed")
#         self.videoFeed = QtWidgets.QLabel(parent=self.centralwidget)
#         self.videoFeed.setGeometry(QtCore.QRect(250, 370, 131, 81))
#         self.videoFeed.setScaledContents(True)
#         self.videoFeed.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
#         self.videoFeed.setWordWrap(True)
#         self.videoFeed.setObjectName("videoFeed")
#         self.recentCommand = QtWidgets.QLabel(parent=self.centralwidget)
#         self.recentCommand.setGeometry(QtCore.QRect(180, 10, 261, 31))
#         self.recentCommand.setScaledContents(True)
#         self.recentCommand.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
#         self.recentCommand.setWordWrap(True)
#         self.recentCommand.setObjectName("recentCommand")
#         self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
#         self.progressBar.setGeometry(QtCore.QRect(250, 200, 141, 31))
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 18))
#         self.menubar.setObjectName("menubar")
#         self.menuFile = QtWidgets.QMenu(parent=self.menubar)
#         self.menuFile.setObjectName("menuFile")
#         self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
#         self.menuHelp.setObjectName("menuHelp")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#         self.actionNew = QtGui.QAction(parent=MainWindow)
#         self.actionNew.setObjectName("actionNew")
#         self.actionOptions = QtGui.QAction(parent=MainWindow)
#         self.actionOptions.setObjectName("actionOptions")
#         self.actionQuit = QtGui.QAction(parent=MainWindow)
#         self.actionQuit.setObjectName("actionQuit")
#         self.actionAbout = QtGui.QAction(parent=MainWindow)
#         self.actionAbout.setObjectName("actionAbout")
#         self.menuFile.addAction(self.actionOptions)
#         self.menuFile.addSeparator()
#         self.menuFile.addAction(self.actionQuit)
#         self.menuFile.addSeparator()
#         self.menuHelp.addAction(self.actionAbout)
#         self.menubar.addAction(self.menuFile.menuAction())
#         self.menubar.addAction(self.menuHelp.menuAction())

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.droneFeed.setText(_translate("MainWindow", "Main drone feed"))
#         self.videoFeed.setText(_translate("MainWindow", "Video feed"))
#         self.recentCommand.setText(_translate("MainWindow", "Recent command"))
#         self.menuFile.setTitle(_translate("MainWindow", "File"))
#         self.menuHelp.setTitle(_translate("MainWindow", "Help"))
#         self.actionNew.setText(_translate("MainWindow", "New "))
#         self.actionOptions.setText(_translate("MainWindow", "Options"))
#         self.actionQuit.setText(_translate("MainWindow", "Quit"))
#         self.actionAbout.setText(_translate("MainWindow", "About"))

    